# Generated by Django 5.2.5 on 2025-08-07 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configapp.driver'),
            preserve_default=False,
        ),
    ]
